accounts/urls.py
from django.contrib.auth.views import login,logout
from django.urls import path
from accounts.views import signup
app_name='accounts'
urlpatterns=[
    path("login", login, {'template_name':'accounts/login.html'}, name="login"),
    path("logout",logout, {'next_page':'/'}, name="logout"),
    path("signup",signup, name="signup")
]

comments/urls.py
from django.urls import path
from comments.views import create_comment

app_name='comments'
urlpatterns=[
    path("createdcomment", create_comment, name="createcomment")
]

compucommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('test/', TemplateView.as_view(template_name="products/test.html")),
    path('accounts/',include('accounts.urls', namespace="accounts")),
    path('comments/',include('comments.urls', namespace="comments")),
    path('', include('products.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

products/urls.py
from django.urls import path
from products.views import HomeView, ProductDetailView, ProductBuyView, search_product, ProductByCategory
urlpatterns=[
    path('', HomeView.as_view(), name="home"),
    path('products/categories/<query>', ProductByCategory.as_view(), name="product_category" ),
    path('search/',search_product , name="search_product"),
    path('products/<slug:slug>/', ProductDetailView.as_view(),name="detail"),
    path('products/<slug:slug>/buy/', ProductBuyView.as_view(),name="buy")
]

accounts/models.py
from django.db import models



comments/models.py
from django.db import models
from django.conf import settings
class Comment(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments'

    )
    product = models.ForeignKey(
        'products.Product',
        related_name='comments',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.content[:23]
        

products/models.py
from django.db import models
from django.urls import reverse
class Product(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.IntegerField()
    slug = models.SlugField()
    categories = models.ManyToManyField('products.ProductCategory')

    def get_absolute_url(self):
        return reverse("detail", kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product=models.ForeignKey(
        'products.Product', on_delete = models.CASCADE,
        related_name='images'
    )
    image = models.ImageField()
    def __str__(self):
        return self.image.url

class ProductCategory(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    def __str__(self):
        return self.name

comments/forms.py
from django import forms
from comments.models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'product']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

def signup(request):
    form = UserCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        password=form.cleaned_data.get('password1')
        username=form.cleaned_data.get('username')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request,"accounts/signup.html", {'form':form})


comments/views.py
from django.shortcuts import render,redirect
 
from comments.forms import CommentForm
from django.http import HttpResponseBadRequest

def create_comment(request):
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.save()
        return redirect(comment.product.get_absolute_url())
    return HttpResponseBadRequest()

products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from products.models import Product
from comments.forms import CommentForm
from django.views.generic.list import ListView
import stripe
from django.conf import settings
from django.http import HttpResponse
class HomeView(TemplateView):
    template_name="products/home.html"
    def get_context_data(self,*args,**kwargs):
        products = Product.objects.all()
        return{'products':products}

class ProductDetailView(DetailView):
    model = Product
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        comment_form=CommentForm()
        context['comment_form'] = comment_form
        return context

def search_product(request):
    query = request.GET.get('query','')
    product = Product.objects.filter(title__icontains = query)
    return render(request,"products/search_product.html",{'product':product})

class ProductByCategory(TemplateView):
    template_name="products/products_by_category.html"
    model = Product
    def get_context_data(self,*args,**kwargs):
        query = kwargs['query']
        products = Product.objects.all()
        return {
        'query':query,
        'products':products
        }



class ProductBuyView(DetailView):
    model = Product
    template_name = 'products/buy.html'
    def post(self,request,*args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY
        token = request.POST['stripeToken']
        product = self.get_object()
        charge = stripe.Charge.create(
            amount = product.price * 100,
            currency = 'USD',
            description = 'cobro por {}'.format(product.title),
            statement_descriptor = "cobro de compusur",
            source = token
        )
        return render(request, "products/success.html", {'debug_info':charge, 'product':product})

accounts/templates/accounts/login.html
{% extends "products/base.html" %}
{% block title %}Login{%endblock%}
{% block content %}
    <div class="row align-items-center">
        <div class="col">
            <h2>Login</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <p><button type="submit" class="btn btn-primary ">Login</button></p>
            </form>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "products/base.html" %}
{% block title%}Registro{% endblock %}
{% block content %}
<div class="content">
    <div class="row">
        <form method="POST">
            <h2>Registro</h2>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">Registrate</button>
            </form>

        </form>

    </div>
</div>
{% endblock %}

products/templates/products/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} CompuSurCommerce {%endblock%}</title>
    <link rel="shortcut icon" href="{% static "image/favicon.ico"%}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    

</head>
<body>

    <header>

        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="navegation">
          <div class="container">

            <a class="navbar-brand" href="{% url "home" %}"><img src="{% static "image/Logo.png"%}" alt="Logo" id="logo-compu"></a>


              <ul class="nav justify-content-end">
                <li class="nav-item dropdown">
                  <div class="dropdown nav-item" >
                    <a class="btn btn-secondary dropdown-toggle " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                      Categorias
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="{% url "product_category" query="Celulares" %}">Celulares</a>
                      <a class="dropdown-item" href="{% url "product_category" query="Computador" %}">Computadoras</a>
                      <a class="dropdown-item" href="{% url "product_category" query="gaming" %}">Gaming</a>


                    </div>
                  </div>
                </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a  class="btn btn-sm btn-primary nav-link" href="{% url "accounts:logout" %}" id="button_logout" style="margin-left:10px">Salir </a>
                    </li>
                    <li class="nav-item">
                        <span id="user" class="nav-link">Bienvenido {{request.user.username}}</span>

                    </li>
                    {% else %}
                  
                    <li class="nav-item" id="login">
                      <a class="nav-link btn btn-sm btn-success" href="{% url "accounts:login" %}" id="login-b">Ingresar</a>
                    </li>
                    <li class="nav-item" id="signup">
                        <a class="nav-link btn btn-sm btn-warning" href="{% url "accounts:signup" %}" id="signup-b">Registrase</a>
                    </li>
                  
                    {% endif %}
              </ul>
            </div>
          </nav>
    </header>
    <div class="jumbotron" id="jombi">
      {% block content %}
      {% endblock content %}
    </div>


    <footer class="footer" id="footer">
        <div class="container">
          <p class="m-0 text-center text-black">Copyright &copy; CompuSur {% now "Y" %}</p>

        </div>
    </footer>
</body>
</html>

products/templates/products/buy.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
<link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">

<style type="text/css">
#product-image {
  max-width: 350px;
}
</style>

{% endblock %}
{% block content %}
<script src="https://js.stripe.com/v3/"data-key="pk_test_zTdZGMyrqMbvI4VxHXPqb1Dl"></script>

<div class="container">

  <div class="row p-3">
		<div class="col-xs-2 m-3 card"><img id="product-image" class="img-responsive" src="{{product.images.first.image.url}}">
		</div>
		<div class="col-xs-4 m-3">
			<h4 class="product-name"><strong>{{object.title}}</strong></h4><h4><small>{{object.description}}</small></h4>
		</div>
	</div>
<div class="row p-2 ">
  <div class="col-xs-12 col-md-6">
  <form action="." method="post" id="payment-form">
    {% csrf_token %}

    <h2>Payment Data</h2>
    <br>
    <div id="card-element">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <div id="card-errors" role="alert"></div>
    <br>
    
    <button type="submit" class="btn btn-success">Buy</button>
  </form>

  </div>
  </div>
</div>


<script type="text/javascript">
var stripe = Stripe('pk_test_zTdZGMyrqMbvI4VxHXPqb1Dl');
var elements = stripe.elements();



var style = {
  base: {
    color: '#32325d',
    lineHeight: '18px',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '20px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};
// Create an instance of the card Element
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>
card.mount('#card-element');

card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});


function stripeTokenHandler(token) {
  console.log(token);
  // // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
// Create a token or display an error when the form is submitted.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the customer that there was an error
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server
      // console.log(result.token);
      stripeTokenHandler(result.token);
    }
  });
});
</script>
{% endblock content %}

products/templates/products/home.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block content %}

    <div class="container" id="containerPrincipal" >
            <h1 class="my-4">Nuestros Productos</h1>
            {% for product in products %}
            {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:"3" %}
            </div>
            {% endif %}
            {% if forloop.counter0|divisibleby:"3" %}
            <div class="row" style="padding-top: 17px" >
            {% endif %}
            <div class="col-lg-4 col-sm-6 portfolio-item" style="padding-top: 17px">
              <div class="card h-100">
                <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.images.first.image.url}}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{{product.get_absolute_url}}">{{product.title}}</a>
                  </h4>
                  <p class="card-text">{{product.description}}</p>
                  
                </div>
              </div>
            </div>
            {% endfor %}
            </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block content %}
    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{product.title}}</h1>

          <!-- Author -->
          <!-- <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p> -->

          <hr>

          <!-- Date/Time -->
          <p>Publicado el {{product.created_at}}</p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{product.images.first.image.url}}" alt="">

          <hr>

          <!-- Post Content -->
          <p class="lead">{{product.description}}</p>

          <hr>

          <!-- Comments Form -->
          {% if request.user.is_authenticated %}
          <h4 id="comments">Comentarios</h4>
          <div class="card my-4">
            <h5 class="card-header">Cuéntanos tu experiencia:</h5>
            <div class="card-body">
              <form method="post" action="{% url "comments:createcomment" %}">
                {% csrf_token %}
                <div class="form-group">
                  <textarea name="{{comment_form.content.name}}" class="form-control" rows="3"></textarea>
                  <input type="hidden" name="{{comment_form.product.name}}" value="{{product.id}}">
                </div>
                <button type="submit" class="btn btn-primary">Enviar</button>
              </form>
            </div>
          </div>
          {% endif %}

          <!-- Single Comment -->
          {% for comment in product.comments.all reversed %}
          <div id="0" class="media mb-4">

            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.author.username}}</h5>
              {{comment.content}}

              <p id="comentario">{{comment.created_at}}</p>

              <hr>
            </div>

          </div>
          {% endfor %}


        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Buscas algo en especial?</h5>
            <div class="card-body">
              <div class="input-group">
                <form class="" action="{% url "search_product" %}" method="GET">
                  <input name="query" type="text" class="form-control" placeholder="Buscar">
                  <button type="submit">Buscar</button>
                  <span class="input-group-btn">
                  </span>
                </form>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categorías</h5>
            <div class="card-body">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    {% for category in product.categories.all %}
                    <li>
                      <a href="{% url "product_category" query=category.name%}">{{category.name}}</a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>

            </div>
          </div>

          <div class="card my-4">
            <h5 class="card-header">Precio</h5>
            <div class="card-body">
              <p>Solo! ${{product.price}}</p>
              <a href="{% url "buy" slug=product.slug %}"><button type="button" class="btn-success btn ">Comprar</button></a>
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

{% endblock %}

products/templates/products/products_by_category.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container" id="containerPrincipal" >
        <h1 class="my-4">Nuestros Productos</h1>
        {% for product in products %}

        {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:"3" %}
        </div>
        {% endif %}
        {% if forloop.counter0|divisibleby:"3" %}

        <div class="row" style="padding-top: 17px" >
        {% endif %}
        {% for category in product.categories.all %}
        {% if category.name == query %}
        <div class="col-lg-4 col-sm-6 portfolio-item" style="padding-top: 17px">

          <div class="card h-100">
            <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.images.first.image.url}}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{{product.get_absolute_url}}">{{product.title}}</a>
              </h4>
              <p class="card-text">{{product.description}}</p>
            </div>
          </div>

        </div>
        {% endif %}
        {% endfor %}
        {% endfor %}
        </div>

{% endblock %}

products/templates/products/search_product.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Compusur</title>
  </head>
  <body>
    <h1>Esto es lo que coincide </h1>
    {% for product in object_list %}
      {{product.title}}
    {% endfor%}




  </body>
</html>

products/templates/products/success.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}
<div class="container">

<div class="row">
  <div class="col-xs-12 col-md-12 m-3">
    <div class="alert alert-info" role="alert">
      <h4 class="alert-heading">Payment success</h4>
      <p>Congratuliations, you just buy {{product.title}}</p>
      <hr>
      <p>DEBUG INFO {{debug_info}}</p>
    </div>
    <a href="/"><button type="button" class="btn btn-primary", name="button">Volver</button></a>
  </div>

</div>
</div>
{% endblock %}

products/templates/products/test.html
{% extends "products/base.html" %}
{% block content %}
<h1>Hello</h1>
{% endblock %}